### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation？

### ISSUE THREAD

**Issue by nightrain-vampire** [buggyyang/CDC_compression#1]
Hello，I want to train the model using my own dataset, but it reports:
![image](https://github.com/buggyyang/CDC_compression/assets/68332728/a17abedb-e7f7-4c9d-9d97-2105cd0d50e3)

What happens? It seems that the diffusion model modifies the tensor with inplace operations. How to solve it?

**Comment by nightrain-vampire** [comment]
> Hello，I want to train the model using my own dataset, but it reports: ![image](https://user-images.githubusercontent.com/68332728/255762367-a17abedb-e7f7-4c9d-9d97-2105cd0d50e3.png)
> 
> What happens? It seems that the diffusion model modifies the tensor with inplace operations. How to solve it?

I have solved it! There are some inplace operations in /modules/network_components.py. You should replace "h += x" with "h = h + x".

**Comment by buggyyang** [comment]
yes. new pytorch version may raise this error, but an older version works fine.
