### ISSUE TITLE
question about quantize

### ISSUE THREAD

**Issue by fivefingerhill** [buggyyang/CDC_compression#10]
Dear author, the paper explains that you add uniform noise to latent during training, but this does not seem to be the case in the code. Which is the correct experimental setting?

This is the quantization in the code:
 q_hyper_latent = quantize(hyper_latent, "dequantize", self.prior.medians)

**Comment by buggyyang** [comment]
Note that there is a self.training flag
```
if self.training:
    q_hyper_latent = quantize(hyper_latent, "noise")
    q_latent = quantize(latent, "noise")
else:
    q_hyper_latent = quantize(hyper_latent, "dequantize", self.prior.medians)
    q_latent = quantize(latent, "dequantize", latent_distribution.mean)
```

**Comment by fivefingerhill** [comment]
I have already made it clear after I asked the teacher brother that day, thank you for such a quick reply.

**Comment by fivefingerhill** [comment]
> Note that there is a self.training flag
> 
> ```
> if self.training:
>     q_hyper_latent = quantize(hyper_latent, "noise")
>     q_latent = quantize(latent, "noise")
> else:
>     q_hyper_latent = quantize(hyper_latent, "dequantize", self.prior.medians)
>     q_latent = quantize(latent, "dequantize", latent_distribution.mean)
> ```


I have already made it clear after I asked the teacher brother that day, thank you for such a quick reply.
