### ISSUE TITLE
Questions about two different parameterizations

### ISSUE THREAD

**Issue by zzzby-star** [buggyyang/CDC_compression#12]
Could the author explain the difference between x_param and epsilon_param? In the paper, there is no detailed introduction to this aspect of thinking. What are the main differences in code?

**Comment by buggyyang** [comment]
Check this paper. https://arxiv.org/pdf/2202.00512. Just two different prediction objective. x predicts the denoised image while epsilon predict the denoiser.

**Comment by zzzby-star** [comment]
Ok, thank you very much for your answer. With best wishes.
