### ISSUE TITLE
Code issues in denoising_diffusion.py

### ISSUE THREAD

**Issue by zzzby-star** [buggyyang/CDC_compression#13]
As shown in the figure, is there a lack of posterior_mean_coef1/posterior_mean_coef2 calculations in the code?
![屏幕截图 2024-05-07 145321](https://github.com/buggyyang/CDC_compression/assets/114472931/d4ddc7ae-cc34-4ae1-8d32-2b25c8609ded)

**Comment by buggyyang** [comment]
The code is for DDPM sampling but we didn't use that
