### ISSUE TITLE
Reproducing x-param results

### ISSUE THREAD

**Issue by Indraa145** [buggyyang/CDC_compression#15]
Hello, thank you for providing the code. I have some question regarding the x-param training code. Does the warm-up phase have a big effect on the result? I tried training the x-param code without the warm-up phase and all I got are gray images. I trained it on the Vimeo90k triplet dataset.

I directly use this command to train the model:
`python train.py --loss_type "l2" --use_weighted_loss --weight_clip 5 --embed_dim 64 --iteration_step 8193 --beta 0.0064 --pred_mode "x" --var_schedule cosine --embd_type "01"`

The results I see in tensorboard from the training code:
![image](https://github.com/buggyyang/CDC_compression/assets/34057268/79d51cf7-72cd-4b86-bff2-a7015f21e482)

![image](https://github.com/buggyyang/CDC_compression/assets/34057268/e6696082-7216-426c-bc75-4f13426d990b)

**Comment by Indraa145** [comment]
Additional question:
For the warm-up phase, is this the correct way of doing it? I got it from your train.sh file
```python train.py --iteration_step 8193  --loss_type "l2" --var_schedule "cosine" --pred_mode "noise" --beta 0.000001 --aux_weight 0.0 --embd_type "01"```

The pred_mode was set to "noise" even in the xparam folder (in the train.sh file). If I want to train the xparam model, do I have to set the pred_mode to "x" in the warm-up phase, or keep it as "noise" during warm-up phase? Thank you

From "train.sh" file inside the "xparam" folder:
![image](https://github.com/buggyyang/CDC_compression/assets/34057268/ef89ac3e-bbd4-462f-9e97-84e66200ea92)

**Comment by buggyyang** [comment]
Hi, thank you for your interest in our project. 
1. Yes, warm-up phase is needed, otherwise the model may converge to some sub-optimal result. But it's weird that your results are just grey images, there should be something. 
2. for xpred model, everthing is "x". And yes, you only need to train a model with a large enough bitrate (beta is as small as possible).
