### ISSUE TITLE
Question about the steps of training and testing

### ISSUE THREAD

**Issue by daixingyu1** [buggyyang/CDC_compression#17]
Hello, I'm sorry to disturb you. I have a few questions about this project that are not clear, please answer them.
 1. What are the training/testing procedures? Or what are the instructions?
 2.  Which folder should the weights after training be placed under the project?
 Looking forward to your reply.

**Comment by buggyyang** [comment]
For model testing, please refer to these [options](https://github.com/buggyyang/CDC_compression/blob/538f0f4fc0fa2c41757dc54547b01d5ae26e9ada/xparam/test_xparam.py#L14-L20) to load the ckpt. The only thing you need to do is to specify the paths for weights and images. For training, we provide the training [code](https://github.com/buggyyang/CDC_compression/blob/main/xparam/train.py) as a reference but you may need to work around to run in your computing environment, as it contains some redundant code snippets and especially the dataloader is only compatible with the data copy on our machine.
