### ISSUE TITLE
How to save encoded bitrate files ?

### ISSUE THREAD

**Issue by Horizonith** [buggyyang/CDC_compression#18]
Your code implementation is very helpful and useful. We can easily get reconstructions and related BPPs using your code.
However, I haven't found any command to save the encoded bitrate files. I want to save them, so I can calculate the actual BPPs, instead of just the estimations in the current output.
thanks

**Comment by buggyyang** [comment]
The actual entropy coding performance was not assessed, usually the overhead is marginal and our main baseline HiFi-GAN is also evaluated in estimated BPP. Should you require this evaluation, it might be necessary to port our entropy model to [CompressAI](https://interdigitalinc.github.io/CompressAI/), which implements a range coder for entropy coding.
