### ISSUE TITLE
About the conditions in the diffusion model

### ISSUE THREAD

**Issue by daixingyu1** [buggyyang/CDC_compression#19]
Dear Author,
Your work has been a tremendous source of inspiration and assistance to me. Currently, I have a question pertaining to diffusion models: Does the scale of latent codes used as conditions influence the quality of image reconstruction? If I were to conduct an experiment to validate this, could you kindly advise on which specific sections or modules of the project I should concentrate on and potentially adjust? Your guidance would be immeasurably valuable in shaping the direction of my research.
I eagerly anticipate your precious insights and wish to express my deepest gratitude in advance for taking the time to read and respond amidst your busy schedule.

**Comment by buggyyang** [comment]
I'm not entirely clear on what you mean by "scale of latent codes." Are you referring to the number of dimensions? If that's the case, this [paper](https://arxiv.org/pdf/1802.01436) in the appendix presents some findings on varying dimensionality. Typically, a high bitrate model necessitates more dimensions to achieve optimal distortion performance. However, the perceptual quality might differ, as a robust diffusion/GAN model can produce "fake" textures that appear perceptually convincing. I'm uncertain about the direction of your research. If your goal is to enhance the architecture, you might explore using transformers, attention mechanisms, etc. If you're aiming for a better compression ratio, more complex autoregressive entropy models or different quantization methods could be considered. For improved perceptual quality, refining the diffusion process could be beneficial. For instance, in my codebase, I experimented with using latent diffusion as the decoder. However, I discovered that while it improved perceptual quality, it tended to stray from "good distortion," leading me to abandon its use. There's indeed a trade-off between [rate, distortion, and perception](https://arxiv.org/abs/1901.07821). Better perception does not equate to better distortion, and there's no definitive answer to this question. You might find this [paper](https://arxiv.org/pdf/2403.04493) insightful.
