### ISSUE TITLE
RuntimeError when launching a training

### ISSUE THREAD

**Issue by marl917** [buggyyang/CDC_compression#2]
Hi,

I tried launching a training with the following arguments:

python train.py --aux_weight 0.9 --aux_loss_type lpips --beta 0.3072 --device 0

But I obtained an error at this line : 
https://github.com/buggyyang/CDC_compression/blob/e5d5e29d9d730c1f2052609bdb29f9fd83a0a647/modules/unet.py#L109 

<img width="1196" alt="image" src="https://github.com/buggyyang/CDC_compression/assets/58914469/03ac5bdc-08c0-4864-a8ed-870a902320cb">

How to solve it ?

**Comment by buggyyang** [comment]
Sorry for the late reply, I'm not sure if you have solved it. It seems there is a shape mismatch between tensors. Maybe you can try to debug it by printing the shape of each tensor? For training, we use 256x256 resolution RGB images, note that the shape of the noise tensor must have the same size.

**Comment by Yolice** [comment]
I also encountered the same problem, you only need to modify this item  【parser.add_argument('--reverse_context_dim_mults', type=int, nargs='+', default=[4, 2],】to 【parser.add_argument('--reverse_context_dim_mults', type=int, nargs='+', default=[4,3,2,1],】 in train.py should be work.
