### ISSUE TITLE
Question about the entropy encoding

### ISSUE THREAD

**Issue by Jaron-U** [buggyyang/CDC_compression#21]
Dear Yang,

Thanks for your excellent work! I have some questions about the code.
1. I did not find the entropy encoding part in the code.
2. Why is the quantization of "dequantize" used directly in the encoder, while in the bpp calculations a distinction is made between quantization methods for training and evaluation.
3. For the quantized results, can I understand that using FlexiblePrior for q_hyper_latent and then using q_hyper_latent to control the results of q_latent? (This question may confuse you, you can just tell me about the connection of these 3 varablies in the code)

Thanks for you help!🙂

**Comment by buggyyang** [comment]
1. We didn't evaluate the entropy coding part. If you need that, you may need to port the model to library such as CompressAI.
2. This distinction is made based on a paper from Google's team. Unfortunately, I forgot the name of the paper, but I think that should be a common method in their transform-coding pipeline.
3. Note that prior is a distribution, latent is some sample. We use hyper_latent to calculate the likelihood under the hyperprior. And we use hyper_latent to obtain the lower-level prior (a conditional prior). Then we use lower level prior+latent to calculate the lower level likelihood. The likelihood is equivalent to bitrate.

**Comment by Jaron-U** [comment]
Thanks for your reply.
What is the $$P(\hat{z})$$ point to in the pseudocode of your paper, is it the likelihood of q_latent?
When you said the lower-level prior, is it the "q_latent" in your code?
Appreciate your help!

**Comment by buggyyang** [comment]
1. As hyper-prior is a widely used concept, we simplified p(z|y)p(y) to p(z) (Here z represents both latents).
2. yes, q_latent is the lower level latent.

**Comment by Jaron-U** [comment]
![1](https://github.com/user-attachments/assets/c5d4a2ae-0947-4b99-8e10-8ddc04648231)
That is, the pseudo-code in the red box is not implemented in the code, right?
$$\hat{z}$$ is the output of the VAE model, and the $$P(\hat{z})$$ is the q_hyper_latent and q_latent?

**Comment by buggyyang** [comment]
yes.
