### ISSUE TITLE
The test file is not adapted to the pre-trained model

### ISSUE THREAD

**Issue by jinhaohust** [buggyyang/CDC_compression#4]
Thank you for your excellent work, would you please update the test file that adapts to your newly given pre-trained model? Thank you!

**Comment by QIN921** [comment]
Has this problem solved? When I try for the pre-trained model, I find that the structure of the pre-trained model seems to be different from the structure of the model in the code. There are no context_fn.enc.x.1.xxx but just context_fn.enc.x.2.xxx in the pre-trained model.
![image](https://github.com/buggyyang/CDC_compression/assets/111260890/07b75682-626c-4243-99dc-bbc51d81e4cd)

**Comment by jinhaohust** [comment]
> Has this problem solved? When I try for the pre-trained model, I find that the structure of the pre-trained model seems to be different from the structure of the model in the code. There are no context_fn.enc.x.1.xxx but just context_fn.enc.x.2.xxx in the pre-trained model. ![image](https://user-images.githubusercontent.com/111260890/284243805-07b75682-626c-4243-99dc-bbc51d81e4cd.png)

The problem hasn't been solved yet, and I'm still trying to figure it out, the author says he'll refine the framework afterward

**Comment by buggyyang** [comment]
just update the codebase. Sorry for the delay. Feel free to make any comment if there is still any problem
