### ISSUE TITLE
sample image

### ISSUE THREAD

**Issue by nessvan** [buggyyang/CDC_compression#5]
Is it normal to get distorted compressed image with purple and cyan patches all over?
I appreciate if you add a sample image and its compressed version to make sure that everything is in place.
Thank you.

**Comment by buggyyang** [comment]
we have sample image in our paper and I'm not sure what you mean by "with purple and cyan patches all over"

**Comment by buggyyang** [comment]
I probably know what you mean. Just remember to clip the pixel values within (0..1) or (0..255) before saving the images. I just updated my code and add some necessary code snippets for loading and saving the images.
