### ISSUE TITLE
About the warm-up phase

### ISSUE THREAD

**Issue by WHUyyx** [buggyyang/CDC_compression#6]
I am interested in the warm-up phase mentioned in your paper. But I do not find that in the code. 
When I ran the training code, I tried to add a 500,000-step warm-up phase, in which I set lambda = 1e-5 and lr = 5e-5. 
In the warm-up phase, I kept the lr constant (and I don't know if it is right).
Unfortunately, I can't get the same result as the model you provided.
So, could you please provide a detailed explanation of the settings for the warm-up phase?

**Comment by buggyyang** [comment]
lr=5e-5 should be fine. Or can you try to use smaller lambda, like 1e-6? Optionally try to warm-up the model for more steps? like 700,000?
