### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by xuyang-C** [buggyyang/CDC_compression#7]
Very impressive work!

Could you please provide a complete dataset? Data paths in load_dataset.py such as "vimeo_septuplet", and "Kodak_rh" are not found. By the way, xparam/modules lacks ae.py.

Many thanks.

**Comment by buggyyang** [comment]
ae.py was not used. All the datasets are publicly available datasets, so you can simply download them from the official source. Like [vimeo](http://toflow.csail.mit.edu/) and [Kodak](https://r0k.us/graphics/kodak/)
