### ISSUE TITLE
Multiple encoder [z1,z2,etc], same embedder (decoder) in the compressor class

### ISSUE THREAD

**Issue by nessvan** [buggyyang/CDC_compression#8]
Great work!
Is there a way to concatenate the latent feature of multiple encoder and use the same decoder to have more control over the nature of latents?
Does it affect the training? Any suggestion on how to efficiently do that?

**Comment by buggyyang** [comment]
You can try it out of course, but we didn't do that, so unfortunately we have no insight about this. The idea seems to be more related to representation learning instead of image compression.
